package:
    name: libhlc
    version: "0.3"

source:
    path: ..

build:
    number: 0
    script_env:
        - LLVM_MAINLINE

about:
    home: https://github.com/numba/libHLC
    license: BSD
    summary: A shared lib that wraps HLC-LLVM from HSAFoundation for code generation to HSA devices
    license_file: LICENSE.TXT
